CREATE TABLE TBLCIDADE (
    IDCIDADE UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CEP VARCHAR(20) NOT NULL,
    UF VARCHAR(2) NOT NULL,
	ATIVO BIT NOT NULL DEFAULT(1)
);

CREATE TABLE TBLCLIENTE (
    IDCLIENTE UNIQUEIDENTIFIER PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
	ATIVO BIT NOT NULL DEFAULT(1)
);

CREATE TABLE TBLENDERECO (
    IDENDERECO UNIQUEIDENTIFIER PRIMARY KEY,
    RUA VARCHAR(70) NOT NULL,
    BAIRRO VARCHAR(70) NOT NULL,
    CEP VARCHAR(20) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    IDCIDADE UNIQUEIDENTIFIER NOT NULL,
    IDCLIENTE UNIQUEIDENTIFIER NOT NULL,
	ATIVO BIT NOT NULL DEFAULT(1)
    FOREIGN KEY (IDCIDADE) REFERENCES TBLCIDADE(IDCIDADE),
    FOREIGN KEY (IDCLIENTE) REFERENCES TBLCLIENTE(IDCLIENTE)
);

CREATE TABLE TBLEQUIPAMENTO (
    IDEQUIPAMENTO UNIQUEIDENTIFIER PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NULL,    
    PRECODIARIO DECIMAL(10, 2) NOT NULL,
    PRECOSEMANAL DECIMAL(10, 2) NOT NULL,
    PRECOMENSAL DECIMAL(10, 2) NOT NULL,
	ATIVO BIT NOT NULL DEFAULT(1)
);

CREATE TABLE TBLORCAMENTO (
    IDORCAMENTO UNIQUEIDENTIFIER PRIMARY KEY,
    IDCLIENTE UNIQUEIDENTIFIER NOT NULL,
    DATAEMISSAO DATETIME2 NOT NULL,
    DATAVALIDADE DATETIME2 NULL,
    STATUS SMALLINT NOT NULL,
    VALORFRETE DECIMAL(10, 2) NOT NULL,
    VALORTOTAL DECIMAL(10, 2) NOT NULL,
	ATIVO BIT NOT NULL DEFAULT(1)
    FOREIGN KEY (IDCLIENTE) REFERENCES TBLCLIENTE(IDCLIENTE)
);

CREATE TABLE TBLITEMORCAMENTO (
    IDITEMORCAMENTO UNIQUEIDENTIFIER PRIMARY KEY,
    IDORCAMENTO UNIQUEIDENTIFIER NOT NULL,
    IDEQUIPAMENTO UNIQUEIDENTIFIER NOT NULL,
    QUANTIDADE INT NOT NULL,
	ATIVO BIT NOT NULL DEFAULT(1)
    FOREIGN KEY (IDORCAMENTO) REFERENCES TBLORCAMENTO(IDORCAMENTO),
    FOREIGN KEY (IDEQUIPAMENTO) REFERENCES TBLEQUIPAMENTO(IDEQUIPAMENTO)
);

CREATE TABLE TBLESTOQUE (
    IDESTOQUE UNIQUEIDENTIFIER PRIMARY KEY,
    IDEQUIPAMENTO UNIQUEIDENTIFIER NOT NULL,
    QUANTIDADEDISPONIVEL INT NOT NULL,
	ATIVO BIT NOT NULL DEFAULT(1)
    FOREIGN KEY (IDEQUIPAMENTO) REFERENCES TBLEQUIPAMENTO(IDEQUIPAMENTO)
);

CREATE TABLE TBLSAIDAEQUIPAMENTO (
    IDSAIDAEQUIPAMENTO UNIQUEIDENTIFIER PRIMARY KEY,
    IDEQUIPAMENTO UNIQUEIDENTIFIER NOT NULL,
    IDORCAMENTO UNIQUEIDENTIFIER NOT NULL,
    DATASAIDA DATETIME2 NOT NULL,
    DATADEVOLUCAO DATETIME2 NOT NULL,
    IDENDERECOSAIDA UNIQUEIDENTIFIER NOT NULL,
	ATIVO BIT NOT NULL DEFAULT(1)
    FOREIGN KEY (IDEQUIPAMENTO) REFERENCES TBLEQUIPAMENTO(IDEQUIPAMENTO),
    FOREIGN KEY (IDORCAMENTO) REFERENCES TBLORCAMENTO(IDORCAMENTO),
    FOREIGN KEY (IDENDERECOSAIDA) REFERENCES TBLENDERECO(IDENDERECO)
);

CREATE TABLE TBLENTRADAEQUIPAMENTO (
    IDENTRADAEQUIPAMENTO UNIQUEIDENTIFIER PRIMARY KEY,
    IDSAIDAEQUIPAMENTO UNIQUEIDENTIFIER NOT NULL,
    DATADEVOLUCAO DATETIME2 NOT NULL,
    OBSERVACAO VARCHAR(255) NULL,
	ATIVO BIT NOT NULL DEFAULT(1),
	DATAALTERACAO DATETIME2 NOT NULL,
    FOREIGN KEY (IDSAIDAEQUIPAMENTO) REFERENCES TBLSAIDAEQUIPAMENTO(IDSAIDAEQUIPAMENTO)
);
